// Generated by CoffeeScript 1.3.3
(function() {
  var BaazarController, MonkeyWrench;

  MonkeyWrench = angular.module('MonkeyWrench');

  BaazarController = (function() {

    BaazarController.$inject = ['$scope', '$routeParams', 'Baazar', 'recipes'];

    function BaazarController(scope, routeParams, Baazar, recipes) {
      this.scope = scope;
      this.routeParams = routeParams;
      this.Baazar = Baazar;
      this.recipes = recipes;
      this.scope.recipes = recipes;
      setTimeout(function() {
        var gg, tab, _i, _len, _ref, _results;
        gg = new CBPGridGallery(document.getElementById('grid-gallery'));
        _ref = document.getElementsByClassName('tabs');
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          tab = _ref[_i];
          _results.push(new CBPFWTabs(tab));
        }
        return _results;
      }, 1000);
      this.scope.msg = "hello world";
    }

    return BaazarController;

  })();

  MonkeyWrench.controller('BaazarController', BaazarController);

}).call(this);
