// Generated by CoffeeScript 1.3.3
(function() {
  var BaazarController, MonkeyWrench;

  MonkeyWrench = angular.module('MonkeyWrench');

  BaazarController = (function() {

    BaazarController.$inject = ['$scope', '$routeParams', 'Baazar', 'recipes', 'userInfo'];

    function BaazarController(scope, routeParams, Baazar, recipes, userInfo) {
      var _this = this;
      this.scope = scope;
      this.routeParams = routeParams;
      this.Baazar = Baazar;
      this.recipes = recipes;
      this.scope.recipes = recipes;
      this.scope.userInfo = userInfo;
      setTimeout(function() {
        var allTabs, gg, tabs, _i, _len, _results;
        gg = new CBPGridGallery(document.getElementById('grid-gallery'));
        allTabs = document.getElementsByClassName('tabs');
        _results = [];
        for (_i = 0, _len = allTabs.length; _i < _len; _i++) {
          tabs = allTabs[_i];
          _results.push(new CBPFWTabs(tabs));
        }
        return _results;
      }, 1000);
      this.scope.msg = "hello world";
      return;
    }

    return BaazarController;

  })();

  MonkeyWrench.controller('BaazarController', BaazarController);

}).call(this);
