// Generated by CoffeeScript 1.3.3
(function() {
  var BodyController, MonkeyWrench;

  MonkeyWrench = angular.module('MonkeyWrench');

  BodyController = (function() {

    BodyController.$inject = ['$scope', '$routeParams', '$timeout', '$location', 'Baazar', 'GPauth', 'Alert', 'Project'];

    function BodyController(scope, routeParams, timeout, location, Baazar, gp, Alert, Project) {
      var _this = this;
      this.scope = scope;
      this.routeParams = routeParams;
      this.timeout = timeout;
      this.location = location;
      this.Baazar = Baazar;
      this.gp = gp;
      this.Alert = Alert;
      this.Project = Project;
      this.alert = this.Alert.bind();
      this.gp.load().then(function() {
        return _this.getUserInfo();
      }, function() {
        _this.user = null;
        _this.signedIn = false;
        return console.log("User not signed in");
      });
      this.scope.$on('$routeChangeSuccess', function(next, current) {
        return _this.showLoader = false;
      });
      this.scope.$on('$routeChangeError', function(next, current) {
        return _this.showLoader = false;
      });
      return;
    }

    BodyController.prototype.getUserInfo = function() {
      var _this = this;
      return this.gp.getUserInfo().then(function(user) {
        _this.user = user;
        _this.signedIn = true;
        _this.showCircle = true;
        return _this.scope.$broadcast('login');
      }, function() {
        return _this.gp.signOut();
      });
    };

    BodyController.prototype.deleteUserInfo = function() {
      this.user = null;
      return this.signedIn = false;
    };

    BodyController.prototype.signIn = function() {
      var _this = this;
      this.showCircle = true;
      this.gp.signIn().then(function() {
        return _this.getUserInfo();
      }, function(error) {
        return console.log(error);
      });
    };

    BodyController.prototype.signOut = function() {
      var _this = this;
      console.log("signing out.....");
      this.gp.signOut().then(function() {
        return console.log("out");
      }, function() {
        return console.log("not out");
      });
      this.user = null;
      this.signedIn = false;
      this.scope.$broadcast('logout');
    };

    BodyController.prototype.home = function() {
      if (this.location.path() === '/') {
        return;
      }
      this.showLoader = true;
      return this.location.path('/');
    };

    BodyController.prototype["new"] = function() {
      if (this.location.path() === '/New') {
        return;
      }
      this.showLoader = true;
      return this.location.path('/New');
    };

    BodyController.prototype.baazar = function() {
      if (this.location.path() === '/Baazar') {
        return;
      }
      this.showLoader = true;
      return this.location.path('/Baazar');
    };

    BodyController.prototype.help = function() {
      if (this.location.path() === '/Help') {
        return;
      }
      this.showLoader = true;
      return this.location.path('/Help');
    };

    BodyController.prototype.handleKeyBoardEvent = function(event) {
      var key, path, sure;
      console.log("Called");
      if (event.ctrlKey || event.metaKey) {
        key = String.fromCharCode(event.which).toLowerCase();
        path = this.location.path();
        console.log(path);
        switch (key) {
          case 's':
            if (path === "/New" || path.indexOf('/Edit') > -1) {
              event.preventDefault();
              return this.scope.$broadcast('save');
            }
            break;
          case 'p':
            event.preventDefault();
            if (path === "/New" || path.indexOf('/Edit') > -1) {
              sure = confirm("Are you sure ? all UNSAVED changes will be lost.!!");
              if (sure) {
                return this["new"]();
              }
            } else {
              return this["new"]();
            }
            break;
          case 'h':
            event.preventDefault();
            return this.home();
          case 'b':
            event.preventDefault();
            return this.baazar();
        }
      }
    };

    return BodyController;

  })();

  MonkeyWrench.controller('BodyController', BodyController);

}).call(this);
