// Generated by CoffeeScript 1.3.3
(function() {
  var MonkeyWrench, NewProjectController;

  MonkeyWrench = angular.module('MonkeyWrench');

  NewProjectController = (function() {

    NewProjectController.$inject = ['$scope', '$routeParams', '$timeout', 'Baazar', 'Project', 'Alert'];

    function NewProjectController(scope, routeParams, timeout, Baazar, Project, Alert) {
      var _this = this;
      this.scope = scope;
      this.routeParams = routeParams;
      this.timeout = timeout;
      this.Baazar = Baazar;
      this.Project = Project;
      this.Alert = Alert;
      this.config = this.Project["new"]();
      this.extjs = null;
      this.extcss = null;
      this.timeout(function() {
        var cbtab, tabs;
        tabs = document.getElementById('form');
        return cbtab = new CBPFWTabs(tabs);
      }, 100, true);
      this.scope.$on('save', function() {
        return _this.save();
      });
      return;
    }

    NewProjectController.prototype.save = function() {
      if (this.config.name === null || this.config.url === null) {
        this.Alert.error("Recipe Name and URL can't be empty..");
        return;
      }
      console.log("saving....");
      this.Project.save(this.config);
      return this.Alert.success("Hurrah....project saved...");
    };

    NewProjectController.prototype.removejs = function(index) {
      return this.config.external.js.splice(index, 1);
    };

    NewProjectController.prototype.addjs = function() {
      if (this.config.external.js.indexOf(this.extjs) === -1 && this.extjs !== null && this.extjs !== void 0) {
        this.config.external.js.push(this.extjs);
      }
      return this.extjs = null;
    };

    NewProjectController.prototype.removecss = function(index) {
      return this.config.external.css.splice(index, 1);
    };

    NewProjectController.prototype.moveUp = function(index, array) {
      var max, temp;
      max = array.length;
      if (index === 0) {
        array.push(array[0]);
        return array.splice(0, 1);
      } else {
        temp = array[index];
        array[index] = array[index - 1];
        return array[index - 1] = temp;
      }
    };

    NewProjectController.prototype.moveDown = function(index, array) {
      var max, temp;
      max = array.length;
      if (index === (max - 1)) {
        return array.unshift(array.pop());
      } else {
        temp = array[index];
        array[index] = array[index + 1];
        return array[index + 1] = temp;
      }
    };

    NewProjectController.prototype.addcss = function() {
      if (this.config.external.css.indexOf(this.extcss) === -1 && this.extcss !== null && this.extcss !== void 0) {
        this.config.external.css.push(this.extcss);
      }
      return this.extcss = null;
    };

    return NewProjectController;

  })();

  MonkeyWrench.controller('NewProjectController', NewProjectController);

}).call(this);
