// Generated by CoffeeScript 1.3.3
(function() {
  var MonkeyWrench, NewProjectController,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  MonkeyWrench = angular.module('MonkeyWrench');

  NewProjectController = (function() {

    NewProjectController.$inject = ['$scope', '$routeParams', 'Baazar', 'Project'];

    function NewProjectController(scope, routeParams, Baazar, Project) {
      var _this = this;
      this.scope = scope;
      this.routeParams = routeParams;
      this.Baazar = Baazar;
      this.create = __bind(this.create, this);

      this.scope.curProject = Project["new"]();
      this.scope.curProject.name = 'parin rocks';
      setTimeout(function() {
        var cbtab, tabs;
        tabs = new CBPFWTabs(document.getElementById('form'));
        return cbtab = new CBPFWTabs(tabs);
      }, 300);
      this.scope.msg = "hello world";
      return;
    }

    NewProjectController.prototype.create = function() {};

    return NewProjectController;

  })();

  MonkeyWrench.controller('NewProjectController', NewProjectController);

}).call(this);
