// Generated by CoffeeScript 1.7.1
var RequestInterceptor;

RequestInterceptor = angular.module('RequestInterceptor', []).config(function($httpProvider) {
  return $httpProvider.interceptors.push('requestInterceptor');
}).factory('requestInterceptor', function($q, $rootScope) {
  var def;
  def = {
    'response': function(response) {
      console.log("[ HTTP => INTERCEPTOR => SUCCESS ]", response);
      return response || $q.when(response);
    }
  };
  return def;
});
