// Generated by CoffeeScript 1.3.3
(function() {
  var RequestInterceptor;

  RequestInterceptor = angular.module('RequestInterceptor', [].config(function($httpProvider) {
    return $httpProvider.interceptors.push('requestInterceptor');
  })).factory('requestInterceptor', function($q, $rootScope) {
    var def;
    def = {
      'response': function(response) {
        console.log("[ HTTP => INTERCEPTOR => SUCCESS ]", response);
        return response || $q.when(response);
      }
    };
    return def;
  });

}).call(this);
