// Generated by CoffeeScript 1.3.3
(function() {
    var MonkeyWrench;

    MonkeyWrench = angular.module('MonkeyWrench', ['ngRoute', 'AuthModule', 'BaazarModule']);

    MonkeyWrench.config([
        '$routeProvider', '$locationProvider',
        function($routeProvider, $locationProvider) {
            $routeProvider.when('/Baazar', {
                templateUrl: '/html/partials/baazar.html',
                controller: 'BaazarController',
                resolve: {
                    recipes: [
                        'Baazar',
                        function(Baazar) {
                            return Baazar.get();
                        }
                    ],
                    userInfo: [
                        'GPauth',
                        function(GPauth) {
                            return GPauth.getUserInfo();
                        }
                    ]
                }
            });
            $locationProvider.html5Mode(false).hashPrefix('!');
        }
    ]);

    MonkeyWrench.run([
        'GPauth',
        function(GPauth) {
            return GPauth.load();
        }
    ]);

}).call(this);
