// Generated by CoffeeScript 1.3.3
(function() {
  var Meta, Schema, logger, metaSchema, mongoose;

  mongoose = require('mongoose');

  logger = require('../utils/logger');

  Schema = mongoose.Schema;

  metaSchema = new Schema({
    _id: {
      type: Schema.Types.ObjectId,
      ref: 'recipe'
    },
    users: {
      type: [
        {
          type: String,
          ref: 'user'
        }
      ],
      "default": []
    },
    favs: {
      type: [
        {
          type: String,
          ref: 'user'
        }
      ],
      "default": []
    },
    karma: {
      type: [
        {
          user: {
            type: String,
            ref: 'user'
          },
          karma: Number
        }
      ],
      "default": []
    }
  });

  metaSchema.virtual('name').get(function() {
    return this.favs;
  });

  Meta = mongoose.model('meta', metaSchema);

  module.exports = Meta;

}).call(this);
