// Generated by CoffeeScript 1.3.3
(function() {
  var logger, meta;

  meta = require('../models/meta');

  logger = require('../utils/logger');

  exports.favourite = function(request, response) {
    var params, query, update, user, _id;
    params = request.body;
    _id = params._id;
    user = params.user;
    logger.info("" + user + " Favorited recipe " + _id);
    query = {
      _id: _id
    };
    update = {
      "$addToSet": {
        favs: user
      }
    };
    return meta.update(query, update, function(error, noOfDocsUpdated) {
      return console.log(user, " Favorited recipe ", _id);
    });
  };

}).call(this);
