// Generated by CoffeeScript 1.3.3
(function() {
  var Meta, Recipe, logger;

  Meta = require('../models/meta');

  Recipe = require('../models/recipe');

  logger = require('../utils/logger');

  exports.favourite = function(request, response) {
    var params, query, update, user, _id;
    params = request.body;
    _id = params._id;
    user = params.user;
    logger.info("" + user + " Favorited recipe " + _id);
    query = {
      _id: _id
    };
    update = {
      "$addToSet": {
        favs: user
      }
    };
    return Meta.update(query, update, function(error, noOfDocsUpdated) {
      return console.log(user, " Favorited recipe ", _id);
    });
  };

  exports.get = function(request, response) {
    var userFilter;
    logger.info("Getting all meta info of all the recipes");
    userFilter = '-authToken -updatedAt';
    return Meta.find({}).populate('_id', '-ingredients').populate('users', userFilter).populate('favs', userFilter).populate('karma._id', userFilter).sort().exec(function(error, recipes) {
      logger.info("sending " + recipes);
      return response.json(recipes, 200);
    });
  };

  exports.karma = function(request, response) {
    var addNewEntry, karma, params, query, user, _id;
    logger.info("[ karma ] START");
    params = request.body;
    _id = params._id;
    user = params.user;
    karma = params.karma;
    logger.info("[ karma ] " + user + " -> " + karma + " -> " + _id);
    addNewEntry = function() {
      var query, updates;
      logger.info("[ addNewEntry ] START adding new entry for " + user + " -> " + karma + " -> " + _id);
      updates = {
        '$addToSet': {
          karma: {
            _id: user,
            karma: karma
          }
        }
      };
      query = {
        _id: _id
      };
      return Meta.update({
        _id: _id
      }, updates, function(error, noOfDocsUpdated) {
        logger.info("[ addNewEntry ] END " + user + " gave " + karma + " to recipe " + _id + " , " + error + ", updated " + noOfDocsUpdated + " docs");
        return response.json({}, 200);
      });
    };
    query = {
      _id: _id,
      'karma._id': user
    };
    Meta.findOne(query, function(error, doc) {
      var entry, i, _i, _len, _ref;
      logger.info("[ karma ] checking if entry exists for " + user + " -> " + karma + " -> " + _id);
      if (error != null) {
        logger.info("[ karma ] END error occurred try later");
        response.json({
          response: "error",
          msg: "Error occurred...try later...:("
        }, 500);
      } else if (doc != null) {
        logger.info("[ karma ] exists !! updating karma for " + _id + " by " + user + " to " + karma);
        _ref = doc.karma;
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          entry = _ref[i];
          if (doc.karma[i]._id === user) {
            doc.karma[i].karma = karma;
            doc.save(function(error, updatedDoc) {
              if (error != null) {
                logger.info("[ karma ] END try again later....");
                return response.json({
                  response: "error",
                  msg: "try again after some time...:("
                }, 500);
              } else {
                logger.info("[ karma ] END " + user + " updated " + _id + "'s karma to " + karma);
                return response.json(updatedDoc, 200);
              }
            });
          }
        }
      } else {
        logger.info("[ karma ] END doesn't exist calling [ addNewEntry ]");
        addNewEntry();
      }
    });
  };

}).call(this);
