// Generated by CoffeeScript 1.3.3
(function() {
  var Meta, Recipe, async, helpers, imgur, insertMetaInfo, logger, path, updateImageLinksInMongo, uploadImagesToImgur;

  Recipe = require('../models/recipe');

  Meta = require('../models/meta');

  imgur = require('imgur-upload');

  async = require('async');

  logger = require('../utils/logger');

  helpers = require('../utils/helpers');

  path = require('path');

  imgur.setClientID('8ef66eb1ddce0cf');

  uploadImagesToImgur = function(files, doneCallback) {
    var asyncTasks, everythingDone, filePaths, img, links, _i, _len;
    logger.info("Trying to upload images to imgur");
    filePaths = [];
    links = [];
    asyncTasks = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      img = files[_i];
      filePaths.push(img.path);
    }
    everythingDone = function() {
      logger.info("doneCallback multiple File upload");
      doneCallback(links);
    };
    logger.info("async started => upload images to imgur");
    async.each(filePaths, function(filePath, callback) {
      imgur.upload(filePath, function(error, response) {
        if (!error && typeof response === "object") {
          links.push(response.data.link);
        } else {
          logger.error("Error uploading file", error, response);
        }
        callback();
      });
    }, everythingDone);
  };

  updateImageLinksInMongo = function(recipe, links) {
    var conditions, options, update;
    conditions = {
      author: recipe.author,
      'ingredients.url': recipe.ingredients.url
    };
    update = {
      "$set": {
        imgs: links
      }
    };
    options = {};
    Recipe.update(conditions, update, options, function(error, noOfDocs) {
      return logger.info("yeah baby.....");
    });
  };

  exports.meta = function(request, recipe) {
    recipe = {
      "_id": request.params.id,
      "author": "parin2092@gmail.com"
    };
    return insertMetaInfo(recipe);
  };

  insertMetaInfo = function(recipe) {
    var meta;
    logger.info("[ insertMetaInfo ] [ START ]");
    meta = {
      _id: recipe._id,
      users: [recipe.author],
      karma: [
        {
          user: recipe.author,
          karma: 8
        }
      ]
    };
    meta = new Meta(meta);
    logger.info("[ insertMetaInfo ] new meta is " + meta);
    logger.info("[ insertMetaInfo ] query for " + meta._id);
    return Meta.findById(meta._id, function(error, recipeMeta) {
      if (recipeMeta != null) {
        logger.info("[ insertMetaInfo ] [ END ] " + meta._id + " already there ");
        return;
      } else {
        logger.info("[ insertMetaInfo ] inserting new");
        meta.save(function(error, recipeMeta) {
          logger.info("[ insertMetaInfo ] [ END ] " + meta._id + " inserted new metainfo " + recipeMeta + " with " + error + " error");
        });
      }
    });
  };

  exports.saveRecipe = function(request, response) {
    var files, id, options, params, recipe, recipeInstance, upsertDate;
    logger.info("[ saveRecipe ] [ START ]");
    params = request.body;
    files = request.files.imgs;
    recipe = params;
    recipe.ingredients = JSON.parse(recipe.ingredients);
    if (recipe.ingredients._id != null) {
      recipe._id = recipe.ingredients._id;
    }
    recipeInstance = new Recipe(recipe);
    id = recipeInstance._id;
    upsertDate = recipeInstance.toObject();
    delete upsertDate._id;
    options = {
      upsert: true,
      'new': true
    };
    logger.info("[ saveRecipe ] do upsert query");
    Recipe.update({
      _id: id
    }, upsertDate, options, function(error, noOfUpdates) {
      var resDoc, _id;
      logger.info("[ saveRecipe ] " + noOfUpdates + " docs updated with error : " + error + " ");
      if (!error) {
        logger.info("[ saveRecipe ] calling [ insertMetaInfo ]");
        insertMetaInfo(recipeInstance);
        logger.info("[ saveRecipe ] 200 sending http response ");
        _id = recipeInstance._id;
        resDoc = {
          response: "success",
          msg: "Successfully shared...",
          _id: _id
        };
        response.json(resDoc, 200);
        logger.info("[ saveRecipe ] 200 response sent ");
        logger.info("200 upload images to imgur");
        uploadImagesToImgur(files, function(links) {
          updateImageLinksInMongo(recipe, links);
        });
      } else {
        logger.error("[ saveRecipe ] hell no this is error : " + error);
        logger.error("[ saveRecipe ] 500 sending http response");
        error = {
          response: "error",
          msg: "Error sharing your recipe."
        };
        response.json(error, 500);
        logger.error("[ saveRecipe ] 500 response sent");
      }
      return;
      return logger.error("[ saveRecipe ] [ END ]");
    });
  };

  exports.comment = function(request, response) {
    var body, comment, params, query, updates, user, _id;
    logger.info("[ comment ] START");
    params = request.body;
    body = params.body;
    user = params.user;
    _id = params._id;
    logger.info("[ comment ] " + user + " commented " + body + " on recipe " + _id);
    query = {
      _id: _id
    };
    comment = {
      body: body,
      user: user,
      date: Date.now()
    };
    updates = {
      '$addToSet': {
        comments: comment
      }
    };
    logger.info("[ comment ] trying to update recipe " + _id);
    return Recipe.update(query, updates, function(error, noOfUpdates) {
      var doc;
      logger.info("[ comment ] ran query for recipe " + _id + " with error: " + error + " and " + noOfUpdates + " updates");
      if (error != null) {
        doc = {
          response: "error",
          msg: "Error occurred try after some time"
        };
        response.json(doc, 500);
        return logger.info("[ comment ] END sending 500");
      } else {
        doc = {
          response: "success",
          msg: "commented Successfully"
        };
        response.json(doc, 200);
        return logger.info("[ comment ] END sending 200");
      }
    });
  };

}).call(this);
