// Generated by CoffeeScript 1.7.1
var User, logger;

User = require('../models/user');

logger = require('../utils/logger');

exports.updateUser = function(req, res) {
  var id, options, upsertDate, user;
  logger.warn("hello there HOW YOU DOING ?");
  options = {
    upsert: true
  };
  user = new User(req.body);
  id = user._id;
  upsertDate = user.toObject();
  delete upsertDate._id;
  logger.info(upsertDate, id);
  return User.update({
    _id: id
  }, upsertDate, options, function(error, noOfUpdates) {
    logger.log(error, noOfUpdates);
    if (!error) {
      logger.info("After update", error, noOfUpdates);
    } else {
      logger.error("Hell no something is seriously wrong");
    }
  });
};
