// Generated by CoffeeScript 1.7.1
(function() {
  var User;

  User = require('../models/user');

  exports.updateUser = function(req, res) {
    var headers, options, update, user, _id;
    options = {
      upsert: true
    };
    user = req.body;
    console.log(user);
    _id = user._id;
    delete user._id;
    update = user;
    headers = {
      'Set-Cookie': 'mycookie=test',
      'Content-Type': 'text/plain'
    };
    res.writeHead(200, headers);
    res.end();
    return;
    return User.findByIdAndUpdate(_id, update, options, function(error, doc) {
      console.log(error, doc, typeof doc);
      if (!error) {
        doc.name = "mayur kataria";
        doc.update(function(error, doc) {
          console.log("After update", error, doc);
        });
      } else {
        user.save(function(error, doc) {
          console.log("New user", error, doc);
        });
      }
    });
  };

}).call(this);
