// Generated by CoffeeScript 1.7.1
var AuthModule, GPauth;

GPauth = (function() {
  function GPauth($http, $q) {
    this.$http = $http;
    this.$q = $q;
    console.log("service intanciated");
    this.START_STATE = 1;
    this.STATE_ACQUIRING_AUTH_TOKEN = 2;
    this.STATE_AUTH_TOKEN_ACQUIRED = 3;
    this.state = this.START_STATE;
    this.authenticationURL = 'https://www.googleapis.com/plus/v1/people/me?fields=aboutMe,displayName,emails,image,url';
    this.accessToken = null;
    this.userInfo = null;
  }

  GPauth.prototype.getState = function() {
    return this.state;
  };

  GPauth.prototype.setUserInfo = function(user) {
    return this.userInfo = {
      _id: user.emails[0]["value"],
      name: user.displayName,
      img: user.image.url,
      authToken: this.accessToken,
      url: user.url
    };
  };

  GPauth.prototype.getToken = function(interactive) {
    var defer, option;
    defer = this.$q.defer();
    this.state = this.STATE_ACQUIRING_AUTH_TOKEN;
    option = {
      interactive: interactive
    };
    chrome.identity.getAuthToken(option, (function(_this) {
      return function(accessToken) {
        if (chrome.runtime.lastError) {
          _this.userInfo = null;
          defer.reject(chrome.runtime.lastError);
        } else {
          _this.accessToken = accessToken;
          defer.resolve();
        }
      };
    })(this));
    return defer.promise;
  };

  GPauth.prototype.requestUserData = function() {
    var config, defer;
    defer = this.$q.defer();
    this.retry = true;
    config = {
      headers: {
        "Authorization": "Bearer " + this.accessToken
      }
    };
    this.$http.get(this.authenticationURL, config).success((function(_this) {
      return function(response, status) {
        if (status === 200) {
          _this.setUserInfo(response);
          _this.state = _this.STATE_AUTH_TOKEN_ACQUIRED;
          defer.resolve(_this.userInfo);
        } else {
          _this.state = _this.START_STATE;
          defer.reject(response);
        }
      };
    })(this)).error((function(_this) {
      return function(response, status) {
        if (_this.retry && status === 401) {
          chrome.identity.removeCachedAuthToken({
            token: _this.accessToken
          }, _this.getToken);
          _this.retry = false;
        }
      };
    })(this));
    return defer.promise;
  };

  GPauth.prototype.getUserInfo = function(interactive) {
    var defer;
    defer = this.$q.defer();
    if (this.state === this.STATE_AUTH_TOKEN_ACQUIRED) {
      defer.resolve(this.userInfo);
    } else {
      return this.requestUserData();
    }
    return defer.promise;
  };

  GPauth.prototype.signIn = function() {
    return this.getToken(true);
  };

  GPauth.prototype.signOut = function() {
    var defer, option, url;
    this.userInfo = null;
    defer = this.$q.defer();
    url = "https://accounts.google.com/o/oauth2/revoke?token=" + this.accessToken;
    option = {
      token: this.accessToken
    };
    chrome.identity.removeCachedAuthToken(option, (function(_this) {
      return function() {
        return _this.$http.get(url).success(defer.resolve).error(defer.reject);
      };
    })(this));
    this.state = this.START_STATE;
    return defer.promise;
  };

  GPauth.prototype.load = function() {
    return this.getToken(false);
  };

  GPauth.prototype.onChange = function(callback) {
    return chrome.identity.onSignInChanged.addListener((function(_this) {
      return function(account, signedIn) {
        console.log("=====================================");
        return console.log("" + account + " is signedIn : " + signedIn);
      };
    })(this));
  };

  return GPauth;

})();

AuthModule = angular.module('AuthModule', []);

AuthModule.service('GPauth', ["$http", "$q", GPauth]);
