// Generated by CoffeeScript 1.3.3
( function ( ) {
    var Project;

    Project = ( function ( ) {

        function Project( ) {}

        Project.prototype.createNew = function ( ) {
            var template;
            return template = {
                name: null,
                url: null,
                external: {
                    js: [ ],
                    css: [ ]
                },
                js: null,
                css: null,
                enabled: true,
                autoApply: false
            };
        };

        return Project;

    } )( );

} )
    .call( this );
